### PR TITLE
feat: LimitOffsetPagination support

### PR DESCRIPTION
**Pull request by matslindh**
This PR adds support for the LimitOffsetPagination module from DRF. I've tried to follow the same logic as the existing Link pagination entries (i.e. not returning anything for the last page if there is only one page, etc.).

Since offset/limit pagination makes it impossible to know the actual number of hits present, I'd suggest either adding a header that contains the total number of hits, or making the `last` entry be a link with `offset` set to the actual count (instead of the last page - but that differs from the behavior seen in the page pagination module).

### CODE REVIEW

**Comment by tbeadle** [comment]
Thanks for doing this! It would be super helpful if you could add some tests and update the README to mention this new class so that people know it exists.

**Comment by matslindh** [comment]
I'll see if I can get that added in a day or two. Do you have any good ideas of how we can communicate "number of hits" out of band? (i.e. the `self.count` value inside the paginator).

**Comment by matslindh** [comment]
I've pushed a small fix to handle the `offset` value for the last page better, as well as added tests and a description in the README.

**Comment by matslindh** [comment]
@tbeadle Anything more you want on this? Any suggestions on how to communicate the total number of hits in a stable and decent way?

**Comment by tbeadle** [comment]
This looks good to me. Nice job on the tests. When I wrote the original version, I was just modeling it after what GitHub uses in their headers, which doesn't include total hit count information, AFAIK. You at least have the limit and offset for the last page, so you have a range that the total hit count could be in. I think that's good enough, at least for me.

**Comment by matslindh** [comment]
Great! Thank you for merging. I'll revisit the total hit count as a `X-Pagination-Total` header (there doesn't seem to be an established standard for adding that information to the request as far as I can tell) later if we find it necessary.

**Pull request merged**
